"""
Script to seed Serie A players into database
Run with: python -m app.scripts.seed_players
"""

import asyncio
import logging
from sqlalchemy import select

from app.db.engine import AsyncSessionLocal
from app.db.models import Team, Player

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Complete Serie A 2024/2025 players data
PLAYERS_DATA = {
    "Inter": [
        {"name": "Yann Sommer", "position": "GK", "number": 1, "nationality": "Switzerland"},
        {"name": "Denzel Dumfries", "position": "DF", "number": 2, "nationality": "Netherlands"},
        {"name": "Stefan de Vrij", "position": "DF", "number": 6, "nationality": "Netherlands"},
        {"name": "Carlos Augusto", "position": "DF", "number": 30, "nationality": "Brazil"},
        {"name": "Benjamin Pavard", "position": "DF", "number": 28, "nationality": "France"},
        {"name": "Alessandro Bastoni", "position": "DF", "number": 95, "nationality": "Italy"},
        {"name": "Francesco Acerbi", "position": "DF", "number": 15, "nationality": "Italy"},
        {"name": "Yann Bisseck", "position": "DF", "number": 31, "nationality": "Germany"},
        {"name": "Matteo Darmian", "position": "DF", "number": 36, "nationality": "Italy"},
        {"name": "Hakan Calhanoglu", "position": "MF", "number": 20, "nationality": "Turkey"},
        {"name": "Henrikh Mkhitaryan", "position": "MF", "number": 22, "nationality": "Armenia"},
        {"name": "Nicolò Barella", "position": "MF", "number": 23, "nationality": "Italy"},
        {"name": "Kristjan Asllani", "position": "MF", "number": 21, "nationality": "Albania"},
        {"name": "Davide Frattesi", "position": "MF", "number": 16, "nationality": "Italy"},
        {"name": "Piotr Zielinski", "position": "MF", "number": 7, "nationality": "Poland"},
        {"name": "Lautaro Martinez", "position": "FW", "number": 10, "nationality": "Argentina"},
        {"name": "Marcus Thuram", "position": "FW", "number": 9, "nationality": "France"},
        {"name": "Mehdi Taremi", "position": "FW", "number": 99, "nationality": "Iran"},
        {"name": "Marko Arnautovic", "position": "FW", "number": 8, "nationality": "Austria"},
        {"name": "Joaquin Correa", "position": "FW", "number": 11, "nationality": "Argentina"},
        {"name": "Josep Martinez", "position": "GK", "number": 13, "nationality": "Spain"},
        {"name": "Raffaele Di Gennaro", "position": "GK", "number": 12, "nationality": "Italy"},
    ],
    "AC Milan": [
        {"name": "Mike Maignan", "position": "GK", "number": 16, "nationality": "France"},
        {"name": "Theo Hernandez", "position": "DF", "number": 19, "nationality": "France"},
        {"name": "Fikayo Tomori", "position": "DF", "number": 23, "nationality": "England"},
        {"name": "Malick Thiaw", "position": "DF", "number": 28, "nationality": "Germany"},
        {"name": "Emerson Royal", "position": "DF", "number": 22, "nationality": "Brazil"},
        {"name": "Davide Calabria", "position": "DF", "number": 2, "nationality": "Italy"},
        {"name": "Strahinja Pavlovic", "position": "DF", "number": 31, "nationality": "Serbia"},
        {"name": "Matteo Gabbia", "position": "DF", "number": 46, "nationality": "Italy"},
        {"name": "Tijjani Reijnders", "position": "MF", "number": 14, "nationality": "Netherlands"},
        {"name": "Youssouf Fofana", "position": "MF", "number": 29, "nationality": "France"},
        {"name": "Ruben Loftus-Cheek", "position": "MF", "number": 8, "nationality": "England"},
        {"name": "Yunus Musah", "position": "MF", "number": 80, "nationality": "USA"},
        {"name": "Christian Pulisic", "position": "FW", "number": 11, "nationality": "USA"},
        {"name": "Rafael Leao", "position": "FW", "number": 10, "nationality": "Portugal"},
        {"name": "Alvaro Morata", "position": "FW", "number": 7, "nationality": "Spain"},
        {"name": "Tammy Abraham", "position": "FW", "number": 90, "nationality": "England"},
        {"name": "Samuel Chukwueze", "position": "FW", "number": 21, "nationality": "Nigeria"},
        {"name": "Noah Okafor", "position": "FW", "number": 17, "nationality": "Switzerland"},
        {"name": "Marco Sportiello", "position": "GK", "number": 57, "nationality": "Italy"},
        {"name": "Lorenzo Torriani", "position": "GK", "number": 96, "nationality": "Italy"},
        {"name": "Filippo Terracciano", "position": "DF", "number": 42, "nationality": "Italy"},
        {"name": "Kevin Zeroli", "position": "MF", "number": 43, "nationality": "Italy"},
    ],
    "Juventus": [
        {"name": "Michele Di Gregorio", "position": "GK", "number": 29, "nationality": "Italy"},
        {"name": "Andrea Cambiaso", "position": "DF", "number": 27, "nationality": "Italy"},
        {"name": "Federico Gatti", "position": "DF", "number": 4, "nationality": "Italy"},
        {"name": "Bremer", "position": "DF", "number": 3, "nationality": "Brazil"},
        {"name": "Pierre Kalulu", "position": "DF", "number": 15, "nationality": "France"},
        {"name": "Danilo", "position": "DF", "number": 6, "nationality": "Brazil"},
        {"name": "Juan Cabal", "position": "DF", "number": 32, "nationality": "Colombia"},
        {"name": "Nicolo Savona", "position": "DF", "number": 37, "nationality": "Italy"},
        {"name": "Manuel Locatelli", "position": "MF", "number": 5, "nationality": "Italy"},
        {"name": "Khephren Thuram", "position": "MF", "number": 19, "nationality": "France"},
        {"name": "Douglas Luiz", "position": "MF", "number": 26, "nationality": "Brazil"},
        {"name": "Weston McKennie", "position": "MF", "number": 16, "nationality": "USA"},
        {"name": "Nicolo Fagioli", "position": "MF", "number": 21, "nationality": "Italy"},
        {"name": "Kenan Yildiz", "position": "FW", "number": 10, "nationality": "Turkey"},
        {"name": "Dusan Vlahovic", "position": "FW", "number": 9, "nationality": "Serbia"},
        {"name": "Timothy Weah", "position": "FW", "number": 22, "nationality": "USA"},
        {"name": "Francisco Conceicao", "position": "FW", "number": 7, "nationality": "Portugal"},
        {"name": "Teun Koopmeiners", "position": "MF", "number": 8, "nationality": "Netherlands"},
        {"name": "Mattia Perin", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Carlo Pinsoglio", "position": "GK", "number": 23, "nationality": "Italy"},
        {"name": "Jonas Rouhi", "position": "DF", "number": 40, "nationality": "Sweden"},
        {"name": "Samuel Mbangula", "position": "FW", "number": 51, "nationality": "Belgium"},
    ],
    "Atalanta": [
        {"name": "Marco Carnesecchi", "position": "GK", "number": 29, "nationality": "Italy"},
        {"name": "Berat Djimsiti", "position": "DF", "number": 19, "nationality": "Albania"},
        {"name": "Sead Kolasinac", "position": "DF", "number": 23, "nationality": "Bosnia"},
        {"name": "Isak Hien", "position": "DF", "number": 4, "nationality": "Sweden"},
        {"name": "Odilon Kossounou", "position": "DF", "number": 3, "nationality": "Ivory Coast"},
        {"name": "Matteo Ruggeri", "position": "DF", "number": 22, "nationality": "Italy"},
        {"name": "Rafael Toloi", "position": "DF", "number": 2, "nationality": "Brazil"},
        {"name": "Ben Godfrey", "position": "DF", "number": 5, "nationality": "England"},
        {"name": "Marten de Roon", "position": "MF", "number": 15, "nationality": "Netherlands"},
        {"name": "Ederson", "position": "MF", "number": 13, "nationality": "Brazil"},
        {"name": "Mario Pasalic", "position": "MF", "number": 8, "nationality": "Croatia"},
        {"name": "Davide Zappacosta", "position": "DF", "number": 77, "nationality": "Italy"},
        {"name": "Raoul Bellanova", "position": "DF", "number": 16, "nationality": "Italy"},
        {"name": "Marco Brescianini", "position": "MF", "number": 6, "nationality": "Italy"},
        {"name": "Charles De Ketelaere", "position": "FW", "number": 17, "nationality": "Belgium"},
        {"name": "Ademola Lookman", "position": "FW", "number": 11, "nationality": "Nigeria"},
        {"name": "Mateo Retegui", "position": "FW", "number": 32, "nationality": "Italy"},
        {"name": "Lazar Samardzic", "position": "MF", "number": 24, "nationality": "Serbia"},
        {"name": "Juan Cuadrado", "position": "MF", "number": 7, "nationality": "Colombia"},
        {"name": "Nicolo Zaniolo", "position": "FW", "number": 10, "nationality": "Italy"},
        {"name": "Francesco Rossi", "position": "GK", "number": 31, "nationality": "Italy"},
        {"name": "Rui Patricio", "position": "GK", "number": 28, "nationality": "Portugal"},
    ],
    "Napoli": [
        {"name": "Alex Meret", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Giovanni Di Lorenzo", "position": "DF", "number": 22, "nationality": "Italy"},
        {"name": "Amir Rrahmani", "position": "DF", "number": 13, "nationality": "Kosovo"},
        {"name": "Alessandro Buongiorno", "position": "DF", "number": 4, "nationality": "Italy"},
        {"name": "Mathias Olivera", "position": "DF", "number": 17, "nationality": "Uruguay"},
        {"name": "Juan Jesus", "position": "DF", "number": 5, "nationality": "Brazil"},
        {"name": "Pasquale Mazzocchi", "position": "DF", "number": 30, "nationality": "Italy"},
        {"name": "Leonardo Spinazzola", "position": "DF", "number": 37, "nationality": "Italy"},
        {"name": "Stanislav Lobotka", "position": "MF", "number": 68, "nationality": "Slovakia"},
        {"name": "Frank Anguissa", "position": "MF", "number": 99, "nationality": "Cameroon"},
        {"name": "Scott McTominay", "position": "MF", "number": 8, "nationality": "Scotland"},
        {"name": "Billy Gilmour", "position": "MF", "number": 6, "nationality": "Scotland"},
        {"name": "Michael Folorunsho", "position": "MF", "number": 90, "nationality": "Italy"},
        {"name": "Khvicha Kvaratskhelia", "position": "FW", "number": 77, "nationality": "Georgia"},
        {"name": "Romelu Lukaku", "position": "FW", "number": 11, "nationality": "Belgium"},
        {"name": "Matteo Politano", "position": "FW", "number": 21, "nationality": "Italy"},
        {"name": "David Neres", "position": "FW", "number": 7, "nationality": "Brazil"},
        {"name": "Giovanni Simeone", "position": "FW", "number": 18, "nationality": "Argentina"},
        {"name": "Giacomo Raspadori", "position": "FW", "number": 81, "nationality": "Italy"},
        {"name": "Elia Caprile", "position": "GK", "number": 25, "nationality": "Italy"},
        {"name": "Nikita Contini", "position": "GK", "number": 12, "nationality": "Italy"},
        {"name": "Cyril Ngonge", "position": "FW", "number": 26, "nationality": "Belgium"},
    ],
    "Lazio": [
        {"name": "Ivan Provedel", "position": "GK", "number": 94, "nationality": "Italy"},
        {"name": "Adam Marusic", "position": "DF", "number": 77, "nationality": "Montenegro"},
        {"name": "Alessio Romagnoli", "position": "DF", "number": 13, "nationality": "Italy"},
        {"name": "Patric", "position": "DF", "number": 4, "nationality": "Spain"},
        {"name": "Nuno Tavares", "position": "DF", "number": 30, "nationality": "Portugal"},
        {"name": "Manuel Lazzari", "position": "DF", "number": 29, "nationality": "Italy"},
        {"name": "Mario Gila", "position": "DF", "number": 34, "nationality": "Spain"},
        {"name": "Luca Pellegrini", "position": "DF", "number": 3, "nationality": "Italy"},
        {"name": "Matteo Guendouzi", "position": "MF", "number": 8, "nationality": "France"},
        {"name": "Nicolo Rovella", "position": "MF", "number": 6, "nationality": "Italy"},
        {"name": "Matias Vecino", "position": "MF", "number": 5, "nationality": "Uruguay"},
        {"name": "Fisayo Dele-Bashiru", "position": "MF", "number": 7, "nationality": "Nigeria"},
        {"name": "Gustav Isaksen", "position": "FW", "number": 18, "nationality": "Denmark"},
        {"name": "Mattia Zaccagni", "position": "FW", "number": 10, "nationality": "Italy"},
        {"name": "Boulaye Dia", "position": "FW", "number": 19, "nationality": "Senegal"},
        {"name": "Taty Castellanos", "position": "FW", "number": 11, "nationality": "Argentina"},
        {"name": "Pedro", "position": "FW", "number": 9, "nationality": "Spain"},
        {"name": "Tijjani Noslin", "position": "FW", "number": 14, "nationality": "Netherlands"},
        {"name": "Christos Mandas", "position": "GK", "number": 35, "nationality": "Greece"},
        {"name": "Luigi Sepe", "position": "GK", "number": 55, "nationality": "Italy"},
        {"name": "Samuel Gigot", "position": "DF", "number": 2, "nationality": "France"},
        {"name": "Gaetano Castrovilli", "position": "MF", "number": 22, "nationality": "Italy"},
    ],
    "AS Roma": [
        {"name": "Mile Svilar", "position": "GK", "number": 99, "nationality": "Belgium"},
        {"name": "Evan Ndicka", "position": "DF", "number": 5, "nationality": "France"},
        {"name": "Gianluca Mancini", "position": "DF", "number": 23, "nationality": "Italy"},
        {"name": "Mats Hummels", "position": "DF", "number": 15, "nationality": "Germany"},
        {"name": "Angelino", "position": "DF", "number": 3, "nationality": "Spain"},
        {"name": "Zeki Celik", "position": "DF", "number": 19, "nationality": "Turkey"},
        {"name": "Mehmet Zeki Celik", "position": "DF", "number": 43, "nationality": "Turkey"},
        {"name": "Mario Hermoso", "position": "DF", "number": 22, "nationality": "Spain"},
        {"name": "Leandro Paredes", "position": "MF", "number": 16, "nationality": "Argentina"},
        {"name": "Bryan Cristante", "position": "MF", "number": 4, "nationality": "Italy"},
        {"name": "Manu Kone", "position": "MF", "number": 17, "nationality": "France"},
        {"name": "Lorenzo Pellegrini", "position": "MF", "number": 7, "nationality": "Italy"},
        {"name": "Niccolo Pisilli", "position": "MF", "number": 61, "nationality": "Italy"},
        {"name": "Paulo Dybala", "position": "FW", "number": 21, "nationality": "Argentina"},
        {"name": "Artem Dovbyk", "position": "FW", "number": 11, "nationality": "Ukraine"},
        {"name": "Stephan El Shaarawy", "position": "FW", "number": 92, "nationality": "Italy"},
        {"name": "Matias Soule", "position": "FW", "number": 18, "nationality": "Argentina"},
        {"name": "Eldor Shomurodov", "position": "FW", "number": 14, "nationality": "Uzbekistan"},
        {"name": "Mathew Ryan", "position": "GK", "number": 89, "nationality": "Australia"},
        {"name": "Renato Marin", "position": "GK", "number": 98, "nationality": "Romania"},
        {"name": "Enzo Le Fee", "position": "MF", "number": 28, "nationality": "France"},
        {"name": "Alexis Saelemaekers", "position": "FW", "number": 56, "nationality": "Belgium"},
    ],
    "Fiorentina": [
        {"name": "David de Gea", "position": "GK", "number": 43, "nationality": "Spain"},
        {"name": "Dodô", "position": "DF", "number": 2, "nationality": "Brazil"},
        {"name": "Luca Ranieri", "position": "DF", "number": 6, "nationality": "Italy"},
        {"name": "Pietro Comuzzo", "position": "DF", "number": 15, "nationality": "Italy"},
        {"name": "Robin Gosens", "position": "DF", "number": 21, "nationality": "Germany"},
        {"name": "Michael Kayode", "position": "DF", "number": 33, "nationality": "Italy"},
        {"name": "Marin Pongracic", "position": "DF", "number": 5, "nationality": "Croatia"},
        {"name": "Fabiano Parisi", "position": "DF", "number": 65, "nationality": "Italy"},
        {"name": "Danilo Cataldi", "position": "MF", "number": 32, "nationality": "Italy"},
        {"name": "Rolando Mandragora", "position": "MF", "number": 8, "nationality": "Italy"},
        {"name": "Yacine Adli", "position": "MF", "number": 29, "nationality": "France"},
        {"name": "Edoardo Bove", "position": "MF", "number": 4, "nationality": "Italy"},
        {"name": "Andrea Colpani", "position": "MF", "number": 23, "nationality": "Italy"},
        {"name": "Riccardo Sottil", "position": "FW", "number": 7, "nationality": "Italy"},
        {"name": "Moise Kean", "position": "FW", "number": 20, "nationality": "Italy"},
        {"name": "Albert Gudmundsson", "position": "FW", "number": 10, "nationality": "Iceland"},
        {"name": "Jonathan Ikone", "position": "FW", "number": 11, "nationality": "France"},
        {"name": "Christian Kouame", "position": "FW", "number": 99, "nationality": "Ivory Coast"},
        {"name": "Pietro Terracciano", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Tommaso Martinelli", "position": "GK", "number": 30, "nationality": "Italy"},
        {"name": "Lucas Martinez Quarta", "position": "DF", "number": 28, "nationality": "Argentina"},
        {"name": "Amir Richardson", "position": "MF", "number": 24, "nationality": "Morocco"},
        {"name": "Roberto Piccoli", "position": "FW", "number": 91, "nationality": "Italy"},
    ],
    "Bologna": [
        {"name": "Lukasz Skorupski", "position": "GK", "number": 28, "nationality": "Poland"},
        {"name": "Stefan Posch", "position": "DF", "number": 3, "nationality": "Austria"},
        {"name": "Sam Beukema", "position": "DF", "number": 31, "nationality": "Netherlands"},
        {"name": "Jhon Lucumi", "position": "DF", "number": 26, "nationality": "Colombia"},
        {"name": "Juan Miranda", "position": "DF", "number": 33, "nationality": "Spain"},
        {"name": "Lorenzo De Silvestri", "position": "DF", "number": 29, "nationality": "Italy"},
        {"name": "Emil Holm", "position": "DF", "number": 2, "nationality": "Sweden"},
        {"name": "Nicolo Casale", "position": "DF", "number": 15, "nationality": "Italy"},
        {"name": "Remo Freuler", "position": "MF", "number": 8, "nationality": "Switzerland"},
        {"name": "Nikola Moro", "position": "MF", "number": 6, "nationality": "Croatia"},
        {"name": "Giovanni Fabbian", "position": "MF", "number": 80, "nationality": "Italy"},
        {"name": "Kacper Urbanski", "position": "MF", "number": 82, "nationality": "Poland"},
        {"name": "Michel Aebischer", "position": "MF", "number": 20, "nationality": "Switzerland"},
        {"name": "Riccardo Orsolini", "position": "FW", "number": 7, "nationality": "Italy"},
        {"name": "Santiago Castro", "position": "FW", "number": 9, "nationality": "Argentina"},
        {"name": "Dan Ndoye", "position": "FW", "number": 11, "nationality": "Switzerland"},
        {"name": "Jens Odgaard", "position": "FW", "number": 21, "nationality": "Denmark"},
        {"name": "Thijs Dallinga", "position": "FW", "number": 24, "nationality": "Netherlands"},
        {"name": "Federico Ravaglia", "position": "GK", "number": 23, "nationality": "Italy"},
        {"name": "Nicola Bagnolini", "position": "GK", "number": 34, "nationality": "Italy"},
        {"name": "Tommaso Pobega", "position": "MF", "number": 18, "nationality": "Italy"},
        {"name": "Charalampos Lykogiannis", "position": "DF", "number": 22, "nationality": "Greece"},
    ],
    "Torino": [
        {"name": "Vanja Milinkovic-Savic", "position": "GK", "number": 32, "nationality": "Serbia"},
        {"name": "Saul Coco", "position": "DF", "number": 23, "nationality": "Equatorial Guinea"},
        {"name": "Adam Masina", "position": "DF", "number": 5, "nationality": "Morocco"},
        {"name": "Sebastian Walukiewicz", "position": "DF", "number": 4, "nationality": "Poland"},
        {"name": "Valentino Lazaro", "position": "DF", "number": 20, "nationality": "Austria"},
        {"name": "Marcus Pedersen", "position": "DF", "number": 16, "nationality": "Norway"},
        {"name": "Mergim Vojvoda", "position": "DF", "number": 27, "nationality": "Kosovo"},
        {"name": "Guillermo Maripan", "position": "DF", "number": 13, "nationality": "Chile"},
        {"name": "Samuele Ricci", "position": "MF", "number": 28, "nationality": "Italy"},
        {"name": "Karol Linetty", "position": "MF", "number": 77, "nationality": "Poland"},
        {"name": "Gvidas Gineitis", "position": "MF", "number": 66, "nationality": "Lithuania"},
        {"name": "Ivan Ilic", "position": "MF", "number": 8, "nationality": "Serbia"},
        {"name": "Adrien Tameze", "position": "MF", "number": 61, "nationality": "France"},
        {"name": "Nikola Vlasic", "position": "FW", "number": 10, "nationality": "Croatia"},
        {"name": "Duvan Zapata", "position": "FW", "number": 91, "nationality": "Colombia"},
        {"name": "Antonio Sanabria", "position": "FW", "number": 9, "nationality": "Paraguay"},
        {"name": "Ché Adams", "position": "FW", "number": 18, "nationality": "Scotland"},
        {"name": "Yann Karamoh", "position": "FW", "number": 7, "nationality": "France"},
        {"name": "Alberto Paleari", "position": "GK", "number": 89, "nationality": "Italy"},
        {"name": "Antonio Donnarumma", "position": "GK", "number": 71, "nationality": "Italy"},
        {"name": "Ali Dembele", "position": "FW", "number": 21, "nationality": "France"},
        {"name": "Alieu Njie", "position": "FW", "number": 14, "nationality": "Sweden"},
    ],
    "Udinese": [
        {"name": "Maduka Okoye", "position": "GK", "number": 40, "nationality": "Nigeria"},
        {"name": "Jaka Bijol", "position": "DF", "number": 29, "nationality": "Slovenia"},
        {"name": "Thomas Kristensen", "position": "DF", "number": 31, "nationality": "Denmark"},
        {"name": "Lautaro Giannetti", "position": "DF", "number": 30, "nationality": "Argentina"},
        {"name": "Kingsley Ehizibue", "position": "DF", "number": 19, "nationality": "Netherlands"},
        {"name": "Jordan Zemura", "position": "DF", "number": 33, "nationality": "Zimbabwe"},
        {"name": "Christian Kabasele", "position": "DF", "number": 27, "nationality": "Belgium"},
        {"name": "Hassane Kamara", "position": "DF", "number": 12, "nationality": "France"},
        {"name": "Jesper Karlstrom", "position": "MF", "number": 25, "nationality": "Sweden"},
        {"name": "Sandi Lovric", "position": "MF", "number": 8, "nationality": "Slovenia"},
        {"name": "Jurgen Ekkelenkamp", "position": "MF", "number": 32, "nationality": "Netherlands"},
        {"name": "Martin Payero", "position": "MF", "number": 5, "nationality": "Argentina"},
        {"name": "Oier Zarraga", "position": "MF", "number": 6, "nationality": "Spain"},
        {"name": "Florian Thauvin", "position": "FW", "number": 10, "nationality": "France"},
        {"name": "Lorenzo Lucca", "position": "FW", "number": 17, "nationality": "Italy"},
        {"name": "Keinan Davis", "position": "FW", "number": 9, "nationality": "England"},
        {"name": "Iker Bravo", "position": "FW", "number": 21, "nationality": "Spain"},
        {"name": "Brenner", "position": "FW", "number": 22, "nationality": "Brazil"},
        {"name": "Daniele Padelli", "position": "GK", "number": 93, "nationality": "Italy"},
        {"name": "Razvan Sava", "position": "GK", "number": 77, "nationality": "Romania"},
        {"name": "Rui Modesto", "position": "DF", "number": 18, "nationality": "Portugal"},
        {"name": "Enzo Ebosse", "position": "DF", "number": 95, "nationality": "Cameroon"},
    ],
    "Empoli": [
        {"name": "Devis Vasquez", "position": "GK", "number": 23, "nationality": "Colombia"},
        {"name": "Mattia Viti", "position": "DF", "number": 21, "nationality": "Italy"},
        {"name": "Ardian Ismajli", "position": "DF", "number": 34, "nationality": "Albania"},
        {"name": "Sebastiano Luperto", "position": "DF", "number": 5, "nationality": "Italy"},
        {"name": "Liberato Cacace", "position": "DF", "number": 13, "nationality": "New Zealand"},
        {"name": "Saba Goglichidze", "position": "DF", "number": 2, "nationality": "Georgia"},
        {"name": "Giuseppe Pezzella", "position": "DF", "number": 3, "nationality": "Italy"},
        {"name": "Tyronne Ebuehi", "position": "DF", "number": 24, "nationality": "Nigeria"},
        {"name": "Alberto Grassi", "position": "MF", "number": 5, "nationality": "Italy"},
        {"name": "Youssef Maleh", "position": "MF", "number": 93, "nationality": "Morocco"},
        {"name": "Faustino Anjorin", "position": "MF", "number": 8, "nationality": "England"},
        {"name": "Tino Anjorin", "position": "MF", "number": 8, "nationality": "England"},
        {"name": "Liam Henderson", "position": "MF", "number": 6, "nationality": "Scotland"},
        {"name": "Jacopo Fazzini", "position": "MF", "number": 21, "nationality": "Italy"},
        {"name": "Emmanuel Ekong", "position": "FW", "number": 11, "nationality": "Nigeria"},
        {"name": "Lorenzo Colombo", "position": "FW", "number": 29, "nationality": "Italy"},
        {"name": "Pietro Pellegri", "position": "FW", "number": 9, "nationality": "Italy"},
        {"name": "Sebastiano Esposito", "position": "FW", "number": 99, "nationality": "Italy"},
        {"name": "Elia Caprile", "position": "GK", "number": 12, "nationality": "Italy"},
        {"name": "Samuele Perisan", "position": "GK", "number": 22, "nationality": "Italy"},
        {"name": "Nicolas Haas", "position": "MF", "number": 32, "nationality": "Switzerland"},
        {"name": "Ola Solbakken", "position": "FW", "number": 17, "nationality": "Norway"},
    ],
    "Parma": [
        {"name": "Zion Suzuki", "position": "GK", "number": 31, "nationality": "Japan"},
        {"name": "Enrico Delprato", "position": "DF", "number": 15, "nationality": "Italy"},
        {"name": "Botond Balogh", "position": "DF", "number": 4, "nationality": "Hungary"},
        {"name": "Emanuele Valeri", "position": "DF", "number": 14, "nationality": "Italy"},
        {"name": "Woyo Couibaly", "position": "DF", "number": 26, "nationality": "Ivory Coast"},
        {"name": "Antoine Hainaut", "position": "DF", "number": 20, "nationality": "France"},
        {"name": "Gianluca Di Chiara", "position": "DF", "number": 3, "nationality": "Italy"},
        {"name": "Alessandro Circati", "position": "DF", "number": 39, "nationality": "Australia"},
        {"name": "Nahuel Estevez", "position": "MF", "number": 8, "nationality": "Argentina"},
        {"name": "Adrian Bernabe", "position": "MF", "number": 10, "nationality": "Spain"},
        {"name": "Simon Sohm", "position": "MF", "number": 19, "nationality": "Switzerland"},
        {"name": "Mandela Keita", "position": "MF", "number": 16, "nationality": "Mali"},
        {"name": "Ange-Yoan Bonny", "position": "FW", "number": 13, "nationality": "Ivory Coast"},
        {"name": "Dennis Man", "position": "FW", "number": 98, "nationality": "Romania"},
        {"name": "Valentin Mihaila", "position": "FW", "number": 28, "nationality": "Romania"},
        {"name": "Gabriel Charpentier", "position": "FW", "number": 30, "nationality": "France"},
        {"name": "Matteo Cancellieri", "position": "FW", "number": 22, "nationality": "Italy"},
        {"name": "Hernani", "position": "MF", "number": 27, "nationality": "Portugal"},
        {"name": "Leandro Chichizola", "position": "GK", "number": 1, "nationality": "Argentina"},
        {"name": "Edoardo Corvi", "position": "GK", "number": 40, "nationality": "Italy"},
        {"name": "Pontus Almqvist", "position": "FW", "number": 11, "nationality": "Sweden"},
        {"name": "Drissa Camara", "position": "MF", "number": 6, "nationality": "Mali"},
    ],
    "Cagliari": [
        {"name": "Simone Scuffet", "position": "GK", "number": 22, "nationality": "Italy"},
        {"name": "Gabriele Zappa", "position": "DF", "number": 28, "nationality": "Italy"},
        {"name": "Yerry Mina", "position": "DF", "number": 26, "nationality": "Colombia"},
        {"name": "Sebastiano Luperto", "position": "DF", "number": 6, "nationality": "Italy"},
        {"name": "Adam Obert", "position": "DF", "number": 33, "nationality": "Slovakia"},
        {"name": "Tommaso Augello", "position": "DF", "number": 3, "nationality": "Italy"},
        {"name": "Paulo Azzi", "position": "DF", "number": 37, "nationality": "Italy"},
        {"name": "Jose Luis Palomino", "position": "DF", "number": 5, "nationality": "Argentina"},
        {"name": "Antoine Makoumbou", "position": "MF", "number": 29, "nationality": "Congo"},
        {"name": "Razvan Marin", "position": "MF", "number": 18, "nationality": "Romania"},
        {"name": "Alessandro Deiola", "position": "MF", "number": 14, "nationality": "Italy"},
        {"name": "Michel Adopo", "position": "MF", "number": 8, "nationality": "Ivory Coast"},
        {"name": "Matteo Prati", "position": "MF", "number": 16, "nationality": "Italy"},
        {"name": "Zito Luvumbo", "position": "FW", "number": 77, "nationality": "Angola"},
        {"name": "Nicolas Viola", "position": "MF", "number": 10, "nationality": "Italy"},
        {"name": "Gianluca Gaetano", "position": "MF", "number": 70, "nationality": "Italy"},
        {"name": "Leonardo Pavoletti", "position": "FW", "number": 30, "nationality": "Italy"},
        {"name": "Alen Sherri", "position": "GK", "number": 1, "nationality": "Albania"},
        {"name": "Giuseppe Ciocci", "position": "GK", "number": 31, "nationality": "Italy"},
        {"name": "Kingstone Mutandwa", "position": "FW", "number": 61, "nationality": "Zimbabwe"},
        {"name": "Mateusz Wieteska", "position": "DF", "number": 24, "nationality": "Poland"},
    ],
    "Lecce": [
        {"name": "Wladimiro Falcone", "position": "GK", "number": 30, "nationality": "Italy"},
        {"name": "Antonino Gallo", "position": "DF", "number": 25, "nationality": "Italy"},
        {"name": "Kialonda Gaspar", "position": "DF", "number": 4, "nationality": "Angola"},
        {"name": "Federico Baschirotto", "position": "DF", "number": 6, "nationality": "Italy"},
        {"name": "Patrick Dorgu", "position": "DF", "number": 13, "nationality": "Denmark"},
        {"name": "Frederic Guilbert", "position": "DF", "number": 12, "nationality": "France"},
        {"name": "Andy Pelmard", "position": "DF", "number": 5, "nationality": "France"},
        {"name": "Balthazar Pierret", "position": "MF", "number": 20, "nationality": "France"},
        {"name": "Ylber Ramadani", "position": "MF", "number": 16, "nationality": "Albania"},
        {"name": "Hamza Rafia", "position": "MF", "number": 8, "nationality": "Tunisia"},
        {"name": "Lassana Coulibaly", "position": "MF", "number": 29, "nationality": "Mali"},
        {"name": "Medon Berisha", "position": "MF", "number": 3, "nationality": "Kosovo"},
        {"name": "Lameck Banda", "position": "FW", "number": 22, "nationality": "Zambia"},
        {"name": "Nikola Krstovic", "position": "FW", "number": 9, "nationality": "Montenegro"},
        {"name": "Santiago Pierotti", "position": "FW", "number": 50, "nationality": "Argentina"},
        {"name": "Tete Morente", "position": "FW", "number": 7, "nationality": "Spain"},
        {"name": "Remi Oudin", "position": "FW", "number": 10, "nationality": "France"},
        {"name": "Nicola Sansone", "position": "FW", "number": 19, "nationality": "Italy"},
        {"name": "Jasper Samooja", "position": "GK", "number": 1, "nationality": "Finland"},
        {"name": "Christian Fruchtl", "position": "GK", "number": 32, "nationality": "Germany"},
        {"name": "Filip Marchwinski", "position": "FW", "number": 18, "nationality": "Poland"},
        {"name": "Luis Hasa", "position": "MF", "number": 27, "nationality": "Italy"},
    ],
    "Como": [
        {"name": "Emil Audero", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Alberto Dossena", "position": "DF", "number": 13, "nationality": "Italy"},
        {"name": "Marc-Oliver Kempf", "position": "DF", "number": 2, "nationality": "Germany"},
        {"name": "Edoardo Goldaniga", "position": "DF", "number": 5, "nationality": "Italy"},
        {"name": "Ignace Van der Brempt", "position": "DF", "number": 77, "nationality": "Belgium"},
        {"name": "Alberto Moreno", "position": "DF", "number": 18, "nationality": "Spain"},
        {"name": "Federico Barba", "position": "DF", "number": 93, "nationality": "Italy"},
        {"name": "Matthias Braunoder", "position": "MF", "number": 23, "nationality": "Austria"},
        {"name": "Sergi Roberto", "position": "MF", "number": 20, "nationality": "Spain"},
        {"name": "Nico Paz", "position": "MF", "number": 79, "nationality": "Argentina"},
        {"name": "Yannik Engelhardt", "position": "MF", "number": 6, "nationality": "Germany"},
        {"name": "Lucas Da Cunha", "position": "MF", "number": 33, "nationality": "France"},
        {"name": "Alieu Fadera", "position": "FW", "number": 16, "nationality": "Gambia"},
        {"name": "Patrick Cutrone", "position": "FW", "number": 10, "nationality": "Italy"},
        {"name": "Andrea Belotti", "position": "FW", "number": 11, "nationality": "Italy"},
        {"name": "Alessio Iovine", "position": "FW", "number": 21, "nationality": "Italy"},
        {"name": "Gabriel Strefezza", "position": "FW", "number": 7, "nationality": "Brazil"},
        {"name": "Luca Mazzitelli", "position": "MF", "number": 36, "nationality": "Italy"},
        {"name": "Pepe Reina", "position": "GK", "number": 25, "nationality": "Spain"},
        {"name": "Jean Butez", "position": "GK", "number": 12, "nationality": "France"},
        {"name": "Maximo Perrone", "position": "MF", "number": 23, "nationality": "Argentina"},
        {"name": "Alessandro Gabrielloni", "position": "FW", "number": 9, "nationality": "Italy"},
    ],
    "Hellas Verona": [
        {"name": "Lorenzo Montipo", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Jackson Tchatchoua", "position": "DF", "number": 38, "nationality": "Cameroon"},
        {"name": "Pawel Dawidowicz", "position": "DF", "number": 27, "nationality": "Poland"},
        {"name": "Giangiacomo Magnani", "position": "DF", "number": 23, "nationality": "Italy"},
        {"name": "Diego Coppola", "position": "DF", "number": 42, "nationality": "Italy"},
        {"name": "Domagoj Bradaric", "position": "DF", "number": 12, "nationality": "Croatia"},
        {"name": "Flavius Daniliuc", "position": "DF", "number": 4, "nationality": "Austria"},
        {"name": "Darko Lazovic", "position": "MF", "number": 8, "nationality": "Serbia"},
        {"name": "Ondrej Duda", "position": "MF", "number": 33, "nationality": "Slovakia"},
        {"name": "Reda Belahyane", "position": "MF", "number": 6, "nationality": "Morocco"},
        {"name": "Suat Serdar", "position": "MF", "number": 25, "nationality": "Germany"},
        {"name": "Tomas Suslov", "position": "MF", "number": 31, "nationality": "Slovakia"},
        {"name": "Abdou Harroui", "position": "MF", "number": 21, "nationality": "Morocco"},
        {"name": "Casper Tengstedt", "position": "FW", "number": 11, "nationality": "Denmark"},
        {"name": "Daniel Mosquera", "position": "FW", "number": 9, "nationality": "Colombia"},
        {"name": "Amin Sarr", "position": "FW", "number": 14, "nationality": "Sweden"},
        {"name": "Dailon Livramento", "position": "FW", "number": 77, "nationality": "Cape Verde"},
        {"name": "Grigoris Kastanos", "position": "MF", "number": 20, "nationality": "Cyprus"},
        {"name": "Simone Perilli", "position": "GK", "number": 22, "nationality": "Italy"},
        {"name": "Alessandro Berardi", "position": "GK", "number": 34, "nationality": "Italy"},
        {"name": "Mathis Lambourde", "position": "DF", "number": 18, "nationality": "France"},
        {"name": "Ayanda Sishuba", "position": "MF", "number": 35, "nationality": "South Africa"},
    ],
    "Genoa": [
        {"name": "Pierluigi Gollini", "position": "GK", "number": 95, "nationality": "Italy"},
        {"name": "Alessandro Vogliacco", "position": "DF", "number": 14, "nationality": "Italy"},
        {"name": "Johan Vasquez", "position": "DF", "number": 22, "nationality": "Mexico"},
        {"name": "Mattia Bani", "position": "DF", "number": 13, "nationality": "Italy"},
        {"name": "Aaron Martin", "position": "DF", "number": 3, "nationality": "Spain"},
        {"name": "Stefano Sabelli", "position": "DF", "number": 20, "nationality": "Italy"},
        {"name": "Brooke Norton-Cuffy", "position": "DF", "number": 59, "nationality": "England"},
        {"name": "Alan Matturro", "position": "DF", "number": 33, "nationality": "Uruguay"},
        {"name": "Morten Frendrup", "position": "MF", "number": 32, "nationality": "Denmark"},
        {"name": "Milan Badelj", "position": "MF", "number": 47, "nationality": "Croatia"},
        {"name": "Morten Thorsby", "position": "MF", "number": 2, "nationality": "Norway"},
        {"name": "Ruslan Malinovskyi", "position": "MF", "number": 17, "nationality": "Ukraine"},
        {"name": "Fabio Miretti", "position": "MF", "number": 23, "nationality": "Italy"},
        {"name": "Andrea Pinamonti", "position": "FW", "number": 19, "nationality": "Italy"},
        {"name": "Vitinha", "position": "FW", "number": 9, "nationality": "Portugal"},
        {"name": "Jeff Ekhator", "position": "FW", "number": 18, "nationality": "Nigeria"},
        {"name": "Caleb Ekuban", "position": "FW", "number": 10, "nationality": "Ghana"},
        {"name": "Mario Balotelli", "position": "FW", "number": 45, "nationality": "Italy"},
        {"name": "Nicola Leali", "position": "GK", "number": 1, "nationality": "Italy"},
        {"name": "Daniele Sommariva", "position": "GK", "number": 39, "nationality": "Italy"},
        {"name": "Patrizio Masini", "position": "MF", "number": 8, "nationality": "Italy"},
        {"name": "Alessandro Zanoli", "position": "DF", "number": 4, "nationality": "Italy"},
    ],
    "Monza": [
        {"name": "Stefano Turati", "position": "GK", "number": 30, "nationality": "Italy"},
        {"name": "Andrea Carboni", "position": "DF", "number": 44, "nationality": "Italy"},
        {"name": "Pablo Mari", "position": "DF", "number": 22, "nationality": "Spain"},
        {"name": "Armando Izzo", "position": "DF", "number": 4, "nationality": "Italy"},
        {"name": "Pedro Pereira", "position": "DF", "number": 19, "nationality": "Portugal"},
        {"name": "Georgios Kyriakopoulos", "position": "DF", "number": 77, "nationality": "Greece"},
        {"name": "Samuele Birindelli", "position": "DF", "number": 2, "nationality": "Italy"},
        {"name": "Danilo D'Ambrosio", "position": "DF", "number": 33, "nationality": "Italy"},
        {"name": "Warren Bondo", "position": "MF", "number": 38, "nationality": "France"},
        {"name": "Alessandro Bianco", "position": "MF", "number": 42, "nationality": "Italy"},
        {"name": "Matteo Pessina", "position": "MF", "number": 32, "nationality": "Italy"},
        {"name": "Andrea Petagna", "position": "FW", "number": 37, "nationality": "Italy"},
        {"name": "Gianluca Caprari", "position": "FW", "number": 10, "nationality": "Italy"},
        {"name": "Daniel Maldini", "position": "FW", "number": 14, "nationality": "Italy"},
        {"name": "Dany Mota", "position": "FW", "number": 47, "nationality": "Portugal"},
        {"name": "Milan Djuric", "position": "FW", "number": 11, "nationality": "Bosnia"},
        {"name": "Mirko Maric", "position": "FW", "number": 20, "nationality": "Croatia"},
        {"name": "Omari Forson", "position": "FW", "number": 24, "nationality": "England"},
        {"name": "Semuel Pizzignacco", "position": "GK", "number": 69, "nationality": "Italy"},
        {"name": "Alessandro Sorrentino", "position": "GK", "number": 21, "nationality": "Italy"},
        {"name": "Stefano Sensi", "position": "MF", "number": 7, "nationality": "Italy"},
        {"name": "Kevin Martins", "position": "FW", "number": 27, "nationality": "Cape Verde"},
    ],
    "Venezia": [
        {"name": "Jesse Joronen", "position": "GK", "number": 1, "nationality": "Finland"},
        {"name": "Jay Idzes", "position": "DF", "number": 4, "nationality": "Netherlands"},
        {"name": "Michael Svoboda", "position": "DF", "number": 30, "nationality": "Czech Republic"},
        {"name": "Ridgeciano Haps", "position": "DF", "number": 5, "nationality": "Netherlands"},
        {"name": "Giorgio Altare", "position": "DF", "number": 15, "nationality": "Italy"},
        {"name": "Francesco Zampano", "position": "DF", "number": 7, "nationality": "Italy"},
        {"name": "Antonio Candela", "position": "DF", "number": 27, "nationality": "France"},
        {"name": "Marin Sverko", "position": "DF", "number": 33, "nationality": "Croatia"},
        {"name": "Magnus Kofod Andersen", "position": "MF", "number": 38, "nationality": "Denmark"},
        {"name": "Hans Nicolussi Caviglia", "position": "MF", "number": 14, "nationality": "Italy"},
        {"name": "Alfred Duncan", "position": "MF", "number": 32, "nationality": "Ghana"},
        {"name": "Mikael Ellertsson", "position": "MF", "number": 77, "nationality": "Iceland"},
        {"name": "Gaetano Oristanio", "position": "FW", "number": 11, "nationality": "Italy"},
        {"name": "Joel Pohjanpalo", "position": "FW", "number": 20, "nationality": "Finland"},
        {"name": "Gianluca Busio", "position": "MF", "number": 6, "nationality": "USA"},
        {"name": "Christian Gytkjaer", "position": "FW", "number": 9, "nationality": "Denmark"},
        {"name": "John Yeboah", "position": "FW", "number": 22, "nationality": "Netherlands"},
        {"name": "Antonio Raimondo", "position": "FW", "number": 29, "nationality": "Italy"},
        {"name": "Filip Stankovic", "position": "GK", "number": 35, "nationality": "Serbia"},
        {"name": "Bruno Bertinato", "position": "GK", "number": 12, "nationality": "Italy"},
        {"name": "Domen Crnigoj", "position": "MF", "number": 33, "nationality": "Slovenia"},
        {"name": "Saad El Haddad", "position": "FW", "number": 21, "nationality": "Morocco"},
    ],
}


async def seed_players():
    """Seed players for all Serie A teams"""
    async with AsyncSessionLocal() as db:
        try:
            # Get all teams from database
            result = await db.execute(select(Team))
            teams = result.scalars().all()

            if not teams:
                logger.error("No teams found in database. Please run seed_teams.py first.")
                return

            # Create a mapping of team names to team objects
            team_map = {team.name: team for team in teams}

            total_players = 0

            for team_name, players_data in PLAYERS_DATA.items():
                team = team_map.get(team_name)

                if not team:
                    logger.warning(f"Team '{team_name}' not found in database. Skipping players.")
                    continue

                logger.info(f"Seeding players for {team_name}...")

                for player_data in players_data:
                    # Check if player already exists (by name only, to handle transfers)
                    result = await db.execute(
                        select(Player).where(
                            Player.name == player_data["name"]
                        )
                    )
                    existing_player = result.scalars().first()

                    if existing_player:
                        if existing_player.team_id != team.id:
                            logger.info(f"Transferring {player_data['name']} from Team {existing_player.team_id} to {team.name} ({team.id})")
                            existing_player.team_id = team.id
                        else:
                            logger.debug(f"Player {player_data['name']} already in correct team. Skipping.")
                        continue

                    # Create new player
                    player = Player(
                        team_id=team.id,
                        name=player_data["name"],
                        position=player_data["position"]
                    )
                    db.add(player)
                    total_players += 1

                await db.commit()
                logger.info(f"Completed seeding players for {team_name}")

            logger.info(f"Successfully seeded {total_players} players across all teams")

        except Exception as e:
            logger.error(f"Error seeding players: {e}")
            await db.rollback()
            raise


if __name__ == "__main__":
    asyncio.run(seed_players())
